var english_sentence = [
	"A beacon does not shine on its base.",
	"A bad workman quarrels with his tools.",
	"A bargain is a bargain.",
	"A barking dog never bites.",
	"A barking dog was never a good hunter.",
	"A man is known by the company he keeps.",
	"A cornered stone meets the mason's chisel.",
	"A leopard cannot change his spots.",
	"An untoward boy may make a good man.",
	"Beginning is half done.",
	"Beware of the wolf in sheep's clothing.",
	"Blood will have blood.",
	"Bad news travels quickly.",
	"Courtesy costs nothing.",
	"Extremes meet.",
	"Empty vessels make the most sound.",
	"Example is better than precept.",
	"Eagles don't catch flies.",
	"Experience is better than learning.",
	"He that will steal a pin will steal an ox.",
	"Half a loaf is better then no bread.",
	"Hunger is the best sauce.",
	"It's the nature of water to run downhill.",
	"Ignorance is bliss.",
	"Ignorance is medicine.",
	"Knowledge brings calamity.",
	"Live as if you were to die tomorrow.",
	"Like father, like son.",
	"Music is the medicine of a troubled mind.",
	"No pain No gain.",
	"No tides wait person.",
	"No house without a mouse.",
	"No rule without exception.",
	"Nobody's perfect.",
	"Negligence is a crime.",
	"Nothing is impossible to a willing heart.",
	"Never shoot, never hit.",
	"Never judge by appearance.",
	"Of a compliment only a third is meant.",
	"Over shoes, over boots.",
	"Our ideals are our better selves.",
	"People who make no noise are dangerous.",
	"Profit is better than fame.",
	"Promise little, do much.",
	"Rome was not built in a day.",
	"Reason rules all things.",
	"Sense comes with age.",
	"Times change, and we change with them.",
	"The world is a wheel.",
	"The dead are soon forgotten.",
	"The first property is the health.",
	"The man of your own trade is your enemy.",
	"The bait hides the hook.",
	"What's done cannot be undone.",
	"You can not make bricks without straw."
];